### ISSUE TITLE
descriptionless errormessage

### ISSUE THREAD

**Issue by EvolverDE** [signum-network/signum-smartj#13]
hi folks,
if i try to publish a test smart contract i get this message:
![bterror](https://user-images.githubusercontent.com/30400562/89122473-ab8dd180-d4c7-11ea-9cdf-9bdab737ae50.jpg)

im using intellyJ IDE

**Comment by jjos2372** [comment]
Hello, sorry for the delay. Is this from one of the standard samples or a modified contract. If modified please also attach the contract code so we can investigate.

**Comment by EvolverDE** [comment]
hi jjos,
i think there is something wrong with the combobox when change the node, can you check this?

**Comment by jjos2372** [comment]
I just tested with a working node and with a node that is not working and the results were as expected with the latest code, so closing this for now.
